; ============================================================
;  features.conf - Funcionalidades de Llamadas
; ============================================================

[general]
pickupexten=*8                      ; Codigo de captura de llamada
featuredigittimeout=1000            ; ms entre digitos de feature
recordingfailsafe=no
atxfernoanswertimeout=15

[featuremap]
blindxfer=##                        ; Transferencia ciega: ##
atxfer=*2                           ; Transferencia asistida: *2
disconnect=*0                       ; Colgar: *0
automon=*1                          ; Iniciar/parar grabacion: *1
parkcall=*5                         ; Estacionar llamada: *5

[applicationmap]
; Funciones adicionales durante la llamada
pauseMonitor => *3,self/callee,PauseMonitor
unpauseMonitor => *4,self/callee,UnpauseMonitor
sendtext => *6,self,AGI(send-sms.agi)

[parkinglot]
parkext=700                         ; Extension para estacionar
parkpos=701-720                     ; Posiciones de estacionamiento
context=internal                    ; Contexto donde se crean
parkingtime=300                     ; Segundos antes de devolver (5 min)
parkedmusicclass=default
findslot=next
parkedcalltransfers=caller
parkedcallreparking=caller
parkedcallhangup=caller
parkedcallrecording=caller
comebacktoorigin=yes
courtesytone=beep
