; ============================================================
;  logger.conf - Registro de Eventos
; ============================================================

[general]
appendhostname=no
dateformat=%F %T
queue_log=yes
queue_log_to_file=yes
queue_log_name=/var/log/asterisk/queue_log
rotatestrategy=rotate
exec_after_rotate=gzip -9 ${filename}.2

[logfiles]
; Consola
console => notice,warning,error,verbose

; Archivo principal
full => notice,warning,error,verbose,debug,dtmf,fax

; Solo errores y advertencias
messages => notice,warning,error

; Log de seguridad (intentos fallidos, etc.)
security => security

; CDR en texto (complementario a cdr_csv)
; cdr-csv generado automaticamente en /var/log/asterisk/cdr-csv/
