; ============================================================
;  musiconhold.conf - Musica en Espera
; ============================================================

[general]
cachertclasses=yes

[default]
mode=files
directory=/var/lib/asterisk/moh/default
random=yes

[ventas]
mode=files
directory=/var/lib/asterisk/moh/ventas
random=yes

[soporte]
mode=files
directory=/var/lib/asterisk/moh/soporte
random=yes

[administracion]
mode=files
directory=/var/lib/asterisk/moh/administracion
random=yes
