; ============================================================
;  rtp.conf - Configuracion de Puertos RTP
;  (Voz y Video pasan por estos puertos - usado por PJSIP)
; ============================================================

[general]
rtpstart=10000
rtpend=20000
rtpchecksums=yes
dtmftimeout=3000
holdtimeout=300
strictrtp=yes                       ; yes = mas seguro con PJSIP + ICE
probationpackets=4
icesupport=yes                      ; ICE para NAT traversal (usado por PJSIP)
stunaddr=stun.l.google.com:19302    ; STUN publico de Google
rtcpinterval=5000

; SRTP (cifrado de medios) - requiere libsrtp2 instalado
; Configurado por endpoint en pjsip.conf con media_encryption=sdes
